#AI Tools

In [53]:
#link to the Kaggle dataset -> https://www.kaggle.com/datasets/devadigax/aitoolbuzz-com-16k-ai-tools-database

import pandas as pd
import numpy as np

##Data Exploration

In [54]:
df_ai_tools = pd.read_csv("/content/AI Tools Dataset 2025 - 16763 Tools from AIToolBuzz.csv")

In [55]:
df_ai_tools.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16762 entries, 0 to 16761
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               16762 non-null  object
 1   Link               16762 non-null  object
 2   Logo               16537 non-null  object
 3   Category           16762 non-null  object
 4   Primary Task       16762 non-null  object
 5   Keywords           9529 non-null   object
 6   Year Founded       5831 non-null   float64
 7   Short Description  16232 non-null  object
 8   Country            6628 non-null   object
 9   industry           7827 non-null   object
 10  technologies       7633 non-null   object
 11  Website            16762 non-null  object
 12  Website Status     16735 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.7+ MB

In [56]:
"""
------------------------------------
Column Descriptions (source: Kaggle)
------------------------------------


Name
    Tool’s official name.

Link
    URL of its page on AIToolBuzz.

Logo
    Direct logo image URL.

Category
    Functional domain (e.g., Communication, Marketing, Development).

Primary Task
    Main purpose or capability.

Keywords
    Comma-separated tags describing tool functions and industries.

Year Founded
    Year of company/tool inception.

Short Description
    Concise summary of the tool.

Country
    Headquarters or operating country.

industry
    Industry classification.

technologies
    Key technologies or frameworks associated.

Website
    Official product/company website.

Website Status
    Website availability (e.g., Active, Error, Not Reachable).
"""

'\n------------------------------------\nColumn Descriptions (source: Kaggle)\n------------------------------------\n\n\nName\n    Tool’s official name.\n\nLink\n    URL of its page on AIToolBuzz.\n\nLogo\n    Direct logo image URL.\n\nCategory\n    Functional domain (e.g., Communication, Marketing, Development).\n\nPrimary Task\n    Main purpose or capability.\n\nKeywords\n    Comma-separated tags describing tool functions and industries.\n\nYear Founded\n    Year of company/tool inception.\n\nShort Description\n    Concise summary of the tool.\n\nCountry\n    Headquarters or operating country.\n\nindustry\n    Industry classification.\n\ntechnologies\n    Key technologies or frameworks associated.\n\nWebsite\n    Official product/company website.\n\nWebsite Status\n    Website availability (e.g., Active, Error, Not Reachable).\n'

In [57]:
df_ai_tools.describe(include='all')

,Name,Link,Logo,Category,Primary Task,Keywords,Year Founded,Short Description,Country,industry,technologies,Website,Website Status
count,16762,16762,16537,16762,16762,9529,5831.000000,16232,6628,7827,7633,16762,16735
unique,16609,16762,16524,14,3495,7875,NaN,16213,99,95,6817,16744,30
top,AI Prompt Generator,https://aitoolbuzz.com/z-ai,https://aitoolbuzz.com/tools/logo/pixelvibe.svg,Media And Content Creation,Content,"technology, information & internet, informatio...",NaN,Chat with your PDFs in seconds.,United States,information technology & services,Mobile Friendly,?ref=aitoolbuzz.com,Active
freq,5,1,2,4289,393,580,NaN,2,3674,5945,85,19,14038
mean,NaN,NaN,NaN,NaN,NaN,NaN,2020.511233,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,4.705878,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,1969.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,2022.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,2023.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,2025.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
columns = [
    'Name', 'Link', 'Logo', 'Category', 'Primary Task', 'Keywords',
    'Year Founded', 'Short Description', 'Country', 'industry',
    'technologies', 'Website', 'Website Status'
]

for col in columns:
    missing = df_ai_tools[col].isna().sum()
    duplicated = df_ai_tools[col].duplicated().sum()
    total_non_null = df_ai_tools[col].count()

    print(f"--- {col} ---")
    print(f"Missing values:        {missing}")
    print(f"Duplicated values:     {duplicated}")
    print(f"Total non-null values: {total_non_null}\n")

--- Name ---
Missing values:        0
Duplicated values:     153
Total non-null values: 16762

--- Link ---
Missing values:        0
Duplicated values:     0
Total non-null values: 16762

--- Logo ---
Missing values:        225
Duplicated values:     237
Total non-null values: 16537

--- Category ---
Missing values:        0
Duplicated values:     16748
Total non-null values: 16762

--- Primary Task ---
Missing values:        0
Duplicated values:     13267
Total non-null values: 16762

--- Keywords ---
Missing values:        7233
Duplicated values:     8886
Total non-null values: 9529

--- Year Founded ---
Missing values:        10931
Duplicated values:     16720
Total non-null values: 5831

--- Short Description ---
Missing values:        530
Duplicated values:     548
Total non-null values: 16232

--- Country ---
Missing values:        10134
Duplicated values:     16662
Total non-null values: 6628

--- industry ---
Missing values:        8935
Duplicated values:     16666
Total non-null values: 7827

--- technologies ---
Missing values:        9129
Duplicated values:     9944
Total non-null values: 7633

--- Website ---
Missing values:        0
Duplicated values:     18
Total non-null values: 16762

--- Website Status ---
Missing values:        27
Duplicated values:     16731
Total non-null values: 16735

##Data Cleaning

In [59]:
#Name column

#Missing values:        0
#Duplicated values:     153
#Total non-null values: 16762

#convert Name to string
df_ai_tools['Name'] = df_ai_tools['Name'].astype(str)

#sometimes CSV or Excel imports add invisible characters that strip() won’t catch
#this keeps only standard ASCII characters
df_ai_tools['Name'] = df_ai_tools['Name'].str.replace(r"[^\x00-\x7F]+", "", regex=True)

In [60]:
#Link column
#example of values -> https://aitoolbuzz.com/chatgpt, https://aitoolbuzz.com/ai-fiesta

#Missing values:        0
#Duplicated values:     0
#Total non-null values: 16609

#convert Link to string
df_ai_tools['Link'] = df_ai_tools['Link'].astype(str)

#regex pattern
pattern_link = r"^https://aitoolbuzz\.com/[A-Za-z0-9-]+$"

#create mask
mask_links = df_ai_tools['Link'].str.match(pattern_link)

#count valid vs invalid
valid_links = mask_links.sum()
invalid_links = (~mask_links).sum()

print(f"Valid Link values: {valid_links}")
print(f"Invalid Link values: {invalid_links}")

#display invalid ones
df_ai_tools.loc[~mask_links, 'Link'].value_counts()

#the 5 "invalid" values that don't match my rule match their respective "Name" entries
#example:
#Link entry: https://aitoolbuzz.com/b^-discover
#Name entry: B^ DISCOVER

Valid Link values: 16757
Invalid Link values: 5

Link
https://aitoolbuzz.com/b^-discover    1
https://aitoolbuzz.com/zoefit_bot     1
https://aitoolbuzz.com/yay!-forms     1
https://aitoolbuzz.com/recipe-now!    1
https://aitoolbuzz.com/go/nogo        1
Name: count, dtype: int64

In [61]:
#Logo column
#example of values -> https://aitoolbuzz.com/tools/logo/deepseek.png, https://aitoolbuzz.com/tools/logo/chatgpt.jpg

#Missing values:        225 (initial -> I converted those values to "nan")
#Duplicated values:     188 (I will not drop duplicates for this column, at least for now)
#Total non-null values: 16537

#convert Logo to string
df_ai_tools['Logo'] = df_ai_tools['Logo'].astype(str)

#when you do .astype(str) before fillna, all NaN values are converted to the string "nan",
#not actual NaN.
#fillna() only replaces real NaN values, not the string "nan"

#handle missing values
#df_ai_tools['Logo'] = df_ai_tools['Logo'].fillna('Unknown')

#regex pattern for Logo URLs
pattern_logo = r"^https://aitoolbuzz\.com/tools/logo/[A-Za-z0-9._-]+\.(png|jpg|jpeg|svg|webp|ai|io|app|com|audio|ico|xyz|art|cc|fm|me|chat|co|dev|energy|in)$"

#create mask
mask_logo = df_ai_tools['Logo'].str.match(pattern_logo)

#count valid vs invalid
valid_logo = mask_logo.sum()
invalid_logo = (~mask_logo).sum()

print(f"Valid Logo values: {valid_logo}")
print(f"Invalid Logo values: {invalid_logo}")

#display invalid logos
df_ai_tools.loc[~mask_logo, 'Logo'].value_counts()

Valid Logo values: 16537
Invalid Logo values: 225

Logo
nan    225
Name: count, dtype: int64

In [62]:
#Category column

#Missing values:        0
#Duplicated values:     16748
#Total non-null values: 16762

#convert Category to string
df_ai_tools['Category'] = df_ai_tools['Category'].astype(str)

df_ai_tools['Category'].value_counts()

Category
Media And Content Creation    4289
Communication And Support     2022
Technology And Development    1739
Operations And Management     1567
Marketing And Sales           1389
Ai And Machine Learning       1320
Business And Finance          1053
Specialized Technologies       967
Data And Analytics             765
Creative And Entertainment     580
Industry Specific              328
Education And Learning         277
Personal And Lifestyle         262
Security And Privacy           204
Name: count, dtype: int64

In [63]:
#Primary Task column

#Missing values:        0
#Duplicated values:     13267
#Total non-null values: 16762

#convert Primary Task to string
df_ai_tools['Primary Task'] = df_ai_tools['Primary Task'].astype(str)

df_ai_tools['Primary Task'].value_counts()

Primary Task
Content                                        393
Images                                         373
Chatbots                                       217
Customer support                               215
Chatting                                       213
                                              ...
Industrial design                                1
Action figures                                   1
Answering questions about the Bhagavad Gita      1
Text-to-image generation                         1
multi models                                     1
Name: count, Length: 3495, dtype: int64

In [64]:
#Keywords column

#Missing values:        7233 (initial)
#Duplicated values:     8886
#Total non-null values: 9529

#convert Keywords to string -> missing values become "nan"
df_ai_tools['Keywords'] = df_ai_tools['Keywords'].astype(str)

df_ai_tools['Keywords'].value_counts()

Keywords
nan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     7233
technology, information & internet, information technology & services                                                                                                                                                                                                                                                                                                                                                                                                                                                    580
software development, information technology & services                                                                                                                                                                                                                                                                                                                                                                                                                                                                  502
it services & it consulting, information technology & services                                                                                                                                                                                                                                                                                                                                                                                                                                                            91
education                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 66
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ...
digital marketing & traditional marketing, marketing services, business startup tools, business intelligence, stress reduction plans, business idea validation, business tools automation, ai-powered business ideation, multi-language support, market research tools, health tech integration, software as a service (saas), business plan development, business growth strategies, wellness app features, guided meditations, business growth tools, business validation tools, entrepreneurship support, online        1
AI, Advertising, Marketing, Ad copy, Creative generation, Automation                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
AI, Image generation, Image editing, Style transfer, Machine learning                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
AI, Cybersecurity, Threat Intelligence, Vulnerability Management, Security Information and Event Management (SIEM), Machine Learning                                                                                                                                                                                                                                                                                                                                                                                       1
AI writing assistant, Grammar checker, Writing tool, Content creation, Productivity, Browser extension, Text editor, Translation tool, Summarizer, Paraphrasing tool                                                                                                                                                                                                                                                                                                                                                       1
Name: count, Length: 7876, dtype: int64

In [71]:
#Year Founded column

#Missing values:        10931 (initial)
#Duplicated values:     16720
#Total non-null values: 5831

#pandas has a special dtype called 'Int64' which supports real integers + NaN
#this automatically converts 2023.0 → 2023 & keeps missing values as <NA>
df_ai_tools['Year Founded'] = df_ai_tools['Year Founded'].astype('Int64')

#df_ai_tools['Year Founded'].isna().sum()
#output -> np.int64(10931)

df_ai_tools['Year Founded'].value_counts()

Year Founded
2023    1726
2024     854
2022     631
2021     458
2020     447
2019     292
2018     226
2017     205
2025     202
2016     158
2015     112
2014     100
2012      74
2013      69
2011      44
2010      34
2009      28
2008      26
2007      21
2006      17
2004      16
2005      16
2000      11
2003      10
2001       8
1998       8
1995       6
1999       5
1997       4
1996       4
2002       4
1993       3
1986       2
1989       2
1983       2
1982       1
1975       1
1994       1
1974       1
1990       1
1969       1
Name: count, dtype: Int64